### ISSUE TITLE
Hide link buttons when empty

### ISSUE THREAD

**Issue by bnovack** [CfABrigadePhiladelphia/laddr#107]
Projects that don't have a Public or Developer site entered get unhelpful "links" that just loop back to the project page. They should be hidden if no value is provided.

**Comment by schlos** [comment]
Hi Ben!
I cant reproduce it on Laddr v2.
For me, on codeforcroatia.org when dev link or public link is empty, no buttons are displayed.

**Comment by titlecharacter** [comment]
Looks like (at least on codeforphilly) it only affects individual project
pages, not the /projects list. Easy fix, just didn't want to forget about
it.
