### ISSUE TITLE
Display tags on profile pages

### ISSUE THREAD

**Issue by titlecharacter** [CfABrigadePhiladelphia/laddr#116]
Brigade members are asked in their signup & profile to identify what topics and tech they're interested in. You can filter the members page by these tags, but they're not actually displayed on profile pages. For example, [this](https://codeforphilly.org/people/chris) profile should make it clear that the user is interested in tech like PHP, and topics including Education and Transit.

**Comment by APrioriRainbows** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redesign project/user tags system](https://trello.com/c/Swu24GNm/6-redesign-project-user-tags-system)
