### ISSUE TITLE
Expose stage and tags at /projects.csv

### ISSUE THREAD

**Issue by ondrae** [CfABrigadePhiladelphia/laddr#118]
Laddr projects now have stages! Great, we've added support for those in the [CfAPI](https://github.com/codeforamerica/cfapi). We'll consume them if you start exposing them in the csv you share with us at https://codeforphilly.org/projects.csv.

The attribute we use for stages is `status`. We've also got support for a comma separated list of `tags`. The docs are at https://github.com/codeforamerica/cfapi#projects-list

You currently have two columns called `category` and `type`. They are now deprecated. We still support them, but we don't use them anywhere for anything. Looking at your csv, neither are you. You can remove those columns.

**Comment by themightychris** [comment]
@ondrae are there any standard values for status?

**Comment by ondrae** [comment]
Hi @themightychris @bennovack 

We're starting with four statuses.
- Experiment
- Alpha
- Beta
- Official

The explanation for them is at http://www.codeforamerica.org/brigade/projects/stages while the guide for how to use them is at https://github.com/codeforamerica/brigade/blob/master/README-Project-Search.md

You can use a different status if you like, it will still show up in our project search.
