### ISSUE TITLE
Add slack channel to project pages

### ISSUE THREAD

**Issue by titlecharacter** [CfABrigadePhiladelphia/laddr#130]
Would be great for projects to be able to list the slack channel they work in. ie, yadaguru has #yadaguru, which is at https://codeforphilly.slack.com/messages/yadaguru/.

**Comment by schlos** [comment]
:+1:

**Comment by schlos** [comment]
@themightychris this is already added (with de6fd34, 7572933, 4e757ea9844ce613903b359c76c2a594de4ba3b1), so I guess this ticket can be closed?

**Comment by aharley40** [comment]
@themightychris bump^
