### ISSUE TITLE
Add Meetup Logo after "Next Meetup" & "Future Meetups"

### ISSUE THREAD

**Issue by yoavzohar** [CfABrigadePhiladelphia/laddr#133]
Add Meetup Logo after "Next Meetup" & "Future Meetups" (see picture below)

![code for philly1](https://cloud.githubusercontent.com/assets/16676913/12311806/d0716dd2-ba27-11e5-9cb2-e77cd89579da.jpg)

**Comment by schlos** [comment]
How do you like this:

![code for croatia staging](https://cloud.githubusercontent.com/assets/1014134/21073331/5a4656f4-bedb-11e6-8d54-f4f9baffac95.jpg)

Note: meetup.com has [rebranded](http://blog.meetup.com/meetup-rebrand/) their logo. This is their new logo.

Code:
<i style="color:#dd3333" class="fa fa-meetup" aria-hidden="true"></i>

If it's fine, let me know and I'll pull it upstream.

**Comment by yoavzohar** [comment]
Looks good
You can pull it upstream

**Comment by schlos** [comment]
@themightychris This can be closed since it was added with https://github.com/schlos/laddr/commit/b82a10aaf4be54b3306cb0874cf2cd84cd2fcbf5
