### ISSUE TITLE
search bar on home page

### ISSUE THREAD

**Issue by jimRsmiley** [CfABrigadePhiladelphia/laddr#14]
Would love to have a search bar to easily search for projects and users.

**Comment by bennovack** [comment]
As of today there's a search bar that seems to search tags, updates, and projects - though not users.

**Comment by themightychris** [comment]
It's currently setup so users are only included in search results if you're logged in. Maybe that policy is worth reconsidering though as the profiles are public anyway and its annoyed me as well a few times to have people not come up because I wasn't logged in

**Comment by titlecharacter** [comment]
@jimRsmiley @themightychris We can close this, right?

**Comment by skiverk** [comment]
Yup, search is working.

Although you have to know that you can scroll down on iOS. I've attached a
screenshot showing no search ATM, you have to scroll down.

Jim
