### ISSUE TITLE
ProjectBuzz title in search results

### ISSUE THREAD

**Issue by schlos** [CfABrigadePhiladelphia/laddr#160]
**Current:**
When searching for term, results for buzzes show always "Laddr\ProjectBuzz #xx"

Example:
![test code for croatia staging](https://cloud.githubusercontent.com/assets/1014134/21073039/2721d59c-bed5-11e6-8f81-e028570682c7.jpg)

Test link: http://staging.codeforcroatia.org/search?q=test

**Expected:**
Project Buzz results should show at least Project name if not Buzz title, same as for Updates.

Example:
Project Name buzz # 1
Project Name2 buzz # 34
...etc

**Comment by themightychris** [comment]
Fixed in 168bd1f
