### ISSUE TITLE
Create New Project Page: Add content space for future "how to" copy.

### ISSUE THREAD

**Issue by rmcmillen50** [CfABrigadePhiladelphia/laddr#163]
Soon, I want to put "getting started advice and instructions" on the Create New Project page. So all we need is the editable markdown 'widget' / area right between the page header and the start of the form.

**Comment by rmcmillen50** [comment]
Assigning Chris hoping that he can very easily knock this one out sooner than later.

**Comment by aharley40** [comment]
@rmcmillen50 After our discussion, I think it'd be faster to request hard-coded solutions if we'd want the project edit page headers to change. Is there a copy ready or could we close this and reopen a new ticket for the copy change?

**Comment by rmcmillen50** [comment]
@aharley40 to make sure i'm following you accurately, you're saying if I wanted to add 3 sentences of body text below, the "Create new project" header, we ought to just hard code it to that page? If so that's cool as I doubt we'll need to change this very often.

**Comment by aharley40** [comment]
If it'll be the same thing every is supposed to see when creating/editing a project then yup.

**Comment by themightychris** [comment]
@aharley40 let's insert a staff-editable markdown content block like the announcement section on the homepage has

**Comment by aharley40** [comment]
@themightychris Gotcha

**Comment by rmcmillen50** [comment]
I thought there was a complexity with doing that @aharley40? That's what I initially asked for and we discussed, no?

**Comment by aharley40** [comment]
@rmcmillen50 Apologies, I'd only ever seen the admin level view, and didn't know the home screen was configurable in the same way.

**Comment by aharley40** [comment]
@rmcmillen50 Available for review at laddr.harley.dev after you've added the following to your host file 138.197.115.229 >harley.dev. If you have your own laddr instance, the branch is issues/163.

**Comment by themightychris** [comment]
Resolved in 74b44192204c4d10a31b3ebb16d85223e1e85eaa and pushed live to cfp.org
