### ISSUE TITLE
Create new Leadership & Support Team Open Roles page

### ISSUE THREAD

**Issue by rmcmillen50** [CfABrigadePhiladelphia/laddr#174]
We need a new page on CodeforPhilly.org that advertises open leadership and support team positions. 

- Like the current Leadership page, this new page should include a single column view of multiple markdown areas. 
- The goal is to have the page header in blue, followed by two major sections of markdown - an area for Leadership Team positions and a 2nd area for support team 
- Separate markdown areas will be needed so that the Leadership team can update roles on the fly, without developer support 

The goal is to link it from multiple pages / menus from our existing site.  (that will be different story)

**Comment by themightychris** [comment]
If this is all you need, you can create it with the built-in CMS tools. Just login and go to /pages

**Comment by rmcmillen50** [comment]
Cool. i had no idea. Will try at lunch today and let you know if I run into issues.
