### ISSUE TITLE
Style search results

### ISSUE THREAD

**Issue by themightychris** [CfABrigadePhiladelphia/laddr#183]
The live search results popup needs some bootstrap 4 love:

<img width="312" alt="screen shot 2018-03-07 at 9 47 31 am" src="https://user-images.githubusercontent.com/458494/37098770-b5592920-21ec-11e8-9642-0d8cf31aca97.png">

**Comment by APrioriRainbows** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate Laddr to Bootstrap 4](https://trello.com/c/OnMsg7ym/2-migrate-laddr-to-bootstrap-4)

**Comment by marcelkooi** [comment]
This is what I'm seeing in the `features/bootstrap4` branch. Is there any more work to do here?

<img width="327" alt="screen shot 2019-02-26 at 7 16 51 pm" src="https://user-images.githubusercontent.com/13142719/53456361-219d2780-39fc-11e9-8503-ef2fe40ba378.png">

**Comment by marcelkooi** [comment]
Handled in https://github.com/CodeForPhilly/laddr/pull/197
