### ISSUE TITLE
Style events list

### ISSUE THREAD

**Issue by themightychris** [CfABrigadePhiladelphia/laddr#184]
Events list needs bootstrap v4 love:

<img width="428" alt="screen shot 2018-03-07 at 9 47 37 am" src="https://user-images.githubusercontent.com/458494/37098995-48d9adbe-21ed-11e8-9cb7-cdee1a5147b6.png">

**Comment by APrioriRainbows** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate Laddr to Bootstrap 4](https://trello.com/c/OnMsg7ym/2-migrate-laddr-to-bootstrap-4)

**Comment by marcelkooi** [comment]
Handled in https://github.com/CodeForPhilly/laddr/pull/197
