### ISSUE TITLE
Style project selector for event checkin

### ISSUE THREAD

**Issue by themightychris** [CfABrigadePhiladelphia/laddr#185]
The selector in this form needs some bootstrap v4 love, it uses bootstrap-combo which might need to be upgraded

<img width="809" alt="screen shot 2018-03-07 at 9 47 52 am" src="https://user-images.githubusercontent.com/458494/37099157-b1d17c48-21ed-11e8-95e3-d69c7f974941.png">

**Comment by APrioriRainbows** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate Laddr to Bootstrap 4](https://trello.com/c/OnMsg7ym/2-migrate-laddr-to-bootstrap-4)

**Comment by chriscauley** [comment]
I can't find this on the site. According to my best search it looks like it is in the home page. how can I trigger it?

**Comment by themightychris** [comment]
Doh! I was supposed to document that in this issue, append `?force_current=1` on the home page to force the site to recognize the next event as currently happening @chriscauley

**Comment by themightychris** [comment]
Here's where that component lives: https://github.com/danielfarrell/bootstrap-combobox

**Comment by marcelkooi** [comment]
Bootstrap 4 branch: https://github.com/danielfarrell/bootstrap-combobox/pull/263
