### ISSUE TITLE
Restore tag fields

### ISSUE THREAD

**Issue by themightychris** [CfABrigadePhiladelphia/laddr#186]
The tag fields on the project edit page and profile edit page rely on bootstrap-tagsinput and typeahead, which probably need some updating to work well with bootstrap v4

<img width="854" alt="screen shot 2018-03-07 at 9 57 53 am" src="https://user-images.githubusercontent.com/458494/37099375-2015f0c6-21ee-11e8-8a54-03d77706719b.png">

**Comment by APrioriRainbows** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate Laddr to Bootstrap 4](https://trello.com/c/OnMsg7ym/2-migrate-laddr-to-bootstrap-4)
