### ISSUE TITLE
Users only blog posts and draft blog posts in homepage activity feed

### ISSUE THREAD

**Issue by schlos** [CfABrigadePhiladelphia/laddr#57]
Homepage feed is listing publicly all blog posts marked as "login required", or ones save as a "draft".

**Comment by themightychris** [comment]
fixed in 51a69d78274234f76f2dc1fbf631fb9310038866

@schlos you'll need to pull it down to your staging site

**Comment by schlos** [comment]
Hi,
Drafts are not displayed in activity feed, thanks for that! But drafts are also not displayed on blog page, so it's hard to find again that saved draft for future re-editing. Can we have hidden draft on activity feed, and display draft on blog page only to user who saved this draft?

Can we have displayed blog posts (Title and post summary) with "Login required" on home activity feed, but only to logged in users?
Something like
```{if $.User}
Title
Post summary
{/if}
```

I've split it into two tickets for easier tracking. Let me know what you think.

Drafts:
- do not display on home page activity feed (keep current implementation)
- show on blog page only to user who wrote draft (current: it's not displayed on blog page), see #63

Members only posts ("login required" posts):
- display in short form on home page activity feed only to logged in users (current: it's not displayed on home activity feed), see #64.
- display using same rule as other posts on blog page (full post), display only to logged in users (keep current implementation)

Thanks,
Miroslav

**Comment by themightychris** [comment]
@schlos currently the home page activity is cached globally so it would be tricky to customize it or specific users. It wouldn't be too tough though to have two separate versions cached for logged in users and the public.

We could include the non-public blog posts in everyone's feed but then vary how they are rendered based on the current user (e.g. show only the summary and a message that you have to login to read it) but I'm not sure it would be clear to authors that the title+summary would be visible to the public for posts marked for logged-in users only.

I'm leaning towards the better solution being to cache two separate activity feeds, one public and one for users, with non-public posts completely invisible to the public. Thoughts?

**Comment by schlos** [comment]
+1 for two separate feeds (A) public and (B) pubic + members only

Displaying public feeds to non-logged in users and displaying all feeds (public + members only) to logged in users is what actually I was trying to say. Seems we're on the same page :)

Having two separate feeds seems like a right implementation.

A) Public activity feed
- is not logged in
- display only public posts

B) Pubic + members only activity feed
- is logged in user
- display public posts
- display members only posts (can we have this posts types colored differently so that it can be differentiated in feed? i.e. title in red or other color, or some icon appended at end of title)
