### ISSUE TITLE
Members avatar overlaps

### ISSUE THREAD

**Issue by schlos** [CfABrigadePhiladelphia/laddr#66]
Members avatars overlaps and extends out of predicted box.

div.thumbnail 170px x 230px
div.avatar 200px x 200px

i.e. http://codeforcroatia.org/people

**Comment by bennovack** [comment]
Chris - you added Help Wanted *after* the fix. What's TBD?

**Comment by themightychris** [comment]
It got entirely busted again in v2 with the bootstrap3 upgrade: https://codeforphilly.org/people

**Comment by titlecharacter** [comment]
Fixed in development and on live sites.
