### ISSUE TITLE
Feature request: If no custom avatar, use gravatar

### ISSUE THREAD

**Issue by schlos** [CfABrigadePhiladelphia/laddr#68]
When user does not upload custom avatar, use gravatar if there is one.

**Comment by schlos** [comment]
Closing, I have missed it in code:
{$src = cat("//www.gravatar.com/avatar/", md5(strtolower($Person->Email)), "?s=", $pixels, "&r=g&d=mm")}

**Comment by themightychris** [comment]
@schlos did you spot it not working anywhere in laddr?

**Comment by schlos** [comment]
@themightychris no, it works, I didnt saw it working so I thought it was not implemented, but later on I found it in code and verified it's working

tnx
