### ISSUE TITLE
laddr.io Domain is expired/no longer pointing at the proper server

### ISSUE THREAD

**Issue by RowdyChildren** [CfABrigadePhiladelphia/laddr#72]
The Laddr.io domain expired at some point and caused out site to produce a lot of errors.
As a workaround (at the suggestion of chris) I edited the hosts file as follows
```162.243.217.26    v1.laddr.io v2.laddr.io```
Chris also suggested modifying the config.json file for each site to point to v1.laddr.us or v2.laddr.us, but I have not tested that yet.

**Comment by titlecharacter** [comment]
Corrected by switching to laddr.us, correct? (@themightychris)

**Comment by themightychris** [comment]
Yep, might re-register the .io one day when it opens for re-registration,
the registrar screwed us over and lost it to the ether
