### ISSUE TITLE
Error after deleting a project

### ISSUE THREAD

**Issue by bennovack** [CfABrigadePhiladelphia/laddr#75]
After visiting /projects/foo/delete, I was presented with a yes/no prompt page, clicked yes, and then got an error page:

Could not find template match for "projectDeleted.tpl", checked paths:

html-templates/projects/not_in_philly/delete/projectDeleted.tpl
html-templates/projects/not_in_philly/projectDeleted.tpl
html-templates/projects/projectDeleted.tpl
html-templates/projectDeleted.tpl

The project does appear to be properly deleted.

**Comment by themightychris** [comment]
This is a cosmetic issue just requiring a simple template to be setup for printing the post-delete status page. One could just copy the *Deleted.tpl for another record type and replace the nouns
