### ISSUE TITLE
Move Members filtering to Members page

### ISSUE THREAD

**Issue by titlecharacter** [CfABrigadePhiladelphia/laddr#88]
The "Members" filtering bar on the left side of the homepage would make more sense if it were shifted onto the [Members page](https://codeforphilly.org/people).
- [ ] Add Members link to top navbar
  - [ ] Move Members filtering sidebar to Members page
  - [ ] Remove Members filtering sidebar from home page

**Comment by schlos** [comment]
@bennovack this has already been added, right?

Currently:
- Members link in top navbar
- members filtering added to /people
- members filtering removed from home sidebar

**Comment by themightychris** [comment]
@schlos yep, good catch!
