### ISSUE TITLE
Move Projects filtering to Projects page

### ISSUE THREAD

**Issue by titlecharacter** [CfABrigadePhiladelphia/laddr#89]
The "Projects" filtering bar on the left side of the homepage would make more sense if it were shifted onto the [Projects page](https://codeforphilly.org/projects).
- [ ] Add Projects link to top navbar
  - [ ] Move Projects filtering sidebar to Members page
  - [ ] Remove Projects filtering sidebar from home page

Code for Charlotte's already done this with their laddr instance, might be a good starting point.

**Comment by schlos** [comment]
@bennovack this has already been added, right?

Currently:
- Projects link in top navbar
- projects filtering added to /projects
- projects filtering removed from home sidebar

**Comment by themightychris** [comment]
@schlos yep, again good catch, thanks!
