### ISSUE TITLE
Display tags under/alongside each project

### ISSUE THREAD

**Issue by titlecharacter** [CfABrigadePhiladelphia/laddr#93]
Tags (Topics, technology, and events) aren't listed on the Projects page or the page for that project. This makes it harder for people to identify the kinds of projects that might interest them.

[ ] Technology, topics, and events listed for each project on Projects page
[ ] Technology, topics, and events listed for each project on that project's individual page

**Comment by APrioriRainbows** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redesign project/user tags system](https://trello.com/c/Swu24GNm/6-redesign-project-user-tags-system)
