### ISSUE TITLE
Status bar on Project page is broken

### ISSUE THREAD

**Issue by titlecharacter** [CfABrigadePhiladelphia/laddr#95]
Each project page has a Status bar that looks like it should grow as a project moves through the stages of development - but it doesn't.

**Comment by laurenancona** [comment]
Eh, I built out the UI element for them back when I started the revamp of project pages for Laddr, but I think those changes got pushed to prod before anyone actually wired them up to the back end.

**Comment by themightychris** [comment]
I pushed everything on your dev site into git, I must have just never
noticed the bar wasn't dynamic yet

**Comment by titlecharacter** [comment]
Now that we're talking about simplifying the formal project status
structure significantly (Idea/In Progress/Deployed, with maybe a side flag
for abandoned/dormant) I wonder if a progress bar is even the best way to
represent that.

**Comment by themightychris** [comment]
I think it would still be valuable as an illustration of how they relate to
each other, out just gets better with the stages simplified

**Comment by laurenancona** [comment]
I was totally on board with fewer statuses (statii?). Another reason for the bar was economy of real estate while still illustrating scale. Plus it gives a little interest to what otherwise can be a fairly dry view, visually.
