### ISSUE TITLE
Upgrading from v1 to v2 made special characters appear wrong

### ISSUE THREAD

**Issue by schlos** [CfABrigadePhiladelphia/laddr#99]
After upgrading, some texts were saved/converted in wrong char encoding, for example:

https://qsnapnet.com/snaps/lcsr9frkjmtxzux

Is there a way to fix it retroactively or to apply fix in code so that it does not happen when somebody else upgrades from v1 to v2?

**Comment by schlos** [comment]
I saw same characters problem in codeforphilly.org

https://qsnapnet.com/snaps/5yoqs8pc1lymbo6
https://qsnapnet.com/snaps/kbvzyv3gpjw3tyb

All snaps: https://qsnapnet.com/folders/lzgzdbb1ezbbj4i

**Comment by titlecharacter** [comment]
https://digwp.com/2011/07/clean-up-weird-characters-in-database/ This may help in cleaning up. Hoping to take a look at this shortly

**Comment by schlos** [comment]
@bennovack thanks for the tip!
I'm testing workaround by replacing characters on database level, seems to be working:
e.g. UPDATE projects SET Title = REPLACE(Title, 'Ä‡', 'ć');

**Comment by themightychris** [comment]
@schlos are you able to input extended characters on the site now and they show up correctly on display and on edit?

**Comment by schlos** [comment]
Hi @themightychris 
Problem was not saving special characters in v2, but historic, already present characters that were stored in v1, somehow after upgrading to v2 they were scrambled in db.

On edit - after saving, chars where stored properly.

Any new text with special characters are displayed good after saving in v2.

So only I will do now (after testing on staging db) - is to replace all scrambled characters with correct ones.

I've seen that this happened also on codeforphilly.org ([example, issuesâ€”a](https://codeforphilly.org/project-buzz/accessibility_in_an_app)), so just heads up - maybe you will need to run replace characters script. This will be reproducible on all Laddr instances that are or will be upgraded from v1 to v2, the script has to be part of upgrade procedure.

I will share script once I've checked all db tables.

**Comment by schlos** [comment]
This is script I've used: 
[replace_characters_script.sql.zip](https://github.com/CfABrigadePhiladelphia/laddr/files/76227/replace_characters_script.sql.zip)
